TRUNCATE TABLE Phong_TrangThai
TRUNCATE TABLE Phong_Default
DELETE Phong
DBCC CHECKIDENT (Phong, RESEED, 1)
TRUNCATE TABLE Phong_TrangThai_Hist
TRUNCATE TABLE TacVu_Hist
TRUNCATE TABLE ThuNhap

DELETE TongThuNhap
DBCC CHECKIDENT (TongThuNhap, RESEED, 1)

TRUNCATE TABLE User_Group_Permission

TRUNCATE TABLE User_Permission

DELETE [USER]
DBCC CHECKIDENT ([User], RESEED, 1)